server:
  port: 8083

spring:
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis-cli?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
  jackson:
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null


logging:
  file:
    name: mp-api.log
    path: ./
  level:
    root: debug
    com.lucaswangdev.mapper: debug
  pattern:
    console: log-%level %msg%n

pegehelper:
  help-dicalect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  row-bounds-uewith-count: tr