package com.lucaswangdev.entity;

/**
* 
* <p>
* User
* </p>
* <p>
* auto generated by jasmine, please do not modify it!
* </p>
*/
public class User {

    /**
    * 
    * type INT
    */
    private Integer id;
    /**
    * 
    * type VARCHAR
    */
    private String userName;
    /**
    * 
    * type VARCHAR
    */
    private String sex;
    /**
    * 
    * type VARCHAR
    */
    private String address;
  
    /**
    * getter 
    */
	public Integer getId() {
		return id;
	}

    /**
    * setter 
    */
	public void setId(Integer id) {
		this.id = id;
	}

    /**
    * getter 
    */
	public String getUserName() {
		return userName;
	}

    /**
    * setter 
    */
	public void setUserName(String userName) {
		this.userName = userName;
	}

    /**
    * getter 
    */
	public String getSex() {
		return sex;
	}

    /**
    * setter 
    */
	public void setSex(String sex) {
		this.sex = sex;
	}

    /**
    * getter 
    */
	public String getAddress() {
		return address;
	}

    /**
    * setter 
    */
	public void setAddress(String address) {
		this.address = address;
	}

  
/** The above part of the comment is auto generated, the following part is written by the user, please do not delete this comment. */

	// 分页-页数
	private Integer pageNo;

	// 分页-每页条数
	private Integer pageSize;

	public Integer getPageNo() {
		return pageNo;
	}

	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}
}