package com.lucaswangdev.entity;

import lombok.Data;

/**
* 
* <p>
* User
* </p>
* <p>
* auto generated by jasmine, please do not modify it!
* </p>
*/
@Data
public class User {

    /**
    * 
    * type INT
    */
    private Integer id;
    /**
    * 
    * type VARCHAR
    */
    private String userName;
    /**
    * 
    * type VARCHAR
    */
    private String sex;
    /**
    * 
    * type VARCHAR
    */
    private String address;
  
/** The above part of the comment is auto generated, the following part is written by the user, please do not delete this comment. */

}