package com.lucaswangdev.mapper;

import com.lucaswangdev.entity.User;
import org.apache.ibatis.annotations.Param;
import java.util.List;

/**
 * UserMapper.
 * auto generated by jasmine, please do not modify it!
 */
public interface UserMapper{
    /**
     * physical delete
     * @param id
     * @return
     */
    int deleteByPrimaryKey(@Param("id") Integer id);


    User selectByPrimaryKey(@Param("id") Integer id);


    /**
     * insert entity
     * @param user
     * @return
     */
    int insert(@Param("user") User user);

    /**
     * insert entity selective.
     * @param user
     * @return
     */
    int insertSelective(@Param("user") User user);


    /**
     * update
     * @param user
     * @return
     */
    int updateByPrimaryKey(@Param("user") User user);

    /**
     * update selective
     * @param user
     * @return
     */
    int updateByPrimaryKeySelective(@Param("user") User user);


/** The above part of the comment is auto generated, the following part is written by the user, please do not delete this comment. */

    User query(@Param("id") Integer id);

    int delete(@Param("id") Integer id);

    /**
     * 通过地址查询用户(分页)
     * @param user
     * @return
     */
    List<User> queryByAddress(@Param("user") User user);
}
